inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Lint/EmptyBlock:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*_spec.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
